language: android
dist: trusty
jdk: oraclejdk8
env:
  global:
  - ANDROID_API_LEVEL=29
  - ANDROID_BUILD_TOOLS_VERSION=29.0.2
  - ANDROID_EMU_API_LEVEL=25
  - ANDROID_ABI=arm64-v8a
  # - ANDROID_ABI=x86_64
  - ADB_INSTALL_TIMEOUT=30
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
before_install:
# - yes | sdkmanager --licenses
- chmod +x gradlew
- android list target



before_script:
  # - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi addon-google_apis-$ANDROID_ABI
  - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI -c 10M
  # - echo no | android create avd --force -n test -t android-$ANDROID_EMU_API_LEVEL --abi google_apis/$ANDROID_ABI -c 100M
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &

script:
  # - ./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace --warning-mode all
  - ./gradlew build installDebug connectedCheck --stacktrace --warning-mode all
  # - ./gradlew connectedCheck -x lint --stacktrace
