language: android
dist: trusty
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-29
    - sys-img-x86-android-29
    
before_install:
- yes | sdkmanager "platforms;android-29"
- chmod +x gradlew

script:
  - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace